### ISSUE TITLE
unable to pull docker image - "no basic auth credentials"

### ISSUE THREAD

**Issue by answerquest** [osrm-decentralized/osrm_IN_docker#12]
`$ sudo docker pull docker.pkg.github.com/osrm-decentralized/osrm_in_docker/osrm_in:latest`

```
Error response from daemon: Get https://docker.pkg.github.com/v2/osrm-decentralized/osrm_in_docker/osrm_in/manifests/latest: no basic auth credentials
```

**Comment by DaxServer** [comment]
Ya, let's put it on Docker Hub

**Comment by DaxServer** [comment]
I've put the image on Docker Hub at https://hub.docker.com/r/sriharithalla/osrm_in
We should not have any more problems now.
