### ISSUE TITLE
india-latest.osrm.fileIndex not downloading due to permissions

### ISSUE THREAD

**Issue by answerquest** [osrm-decentralized/osrm_IN_docker#13]
```
# docker run --rm -it -p 5000:5000 -v "${PWD}/data:/data" osrm_in
[warn] Missing/Broken File: /data/india-latest.osrm.fileIndex
[error] Required files are missing, cannot continue
```

When building from source i'm noticing this `.osrm.fileIndex` file is always created, it's almost as big as the original .pbf, and it has different permissions: 700 (only owner, no perms for group or public). 

So it's probably there on your server but the https://files.sriharithalla.com/routing/india/ webserver can't see it due to no read permissions.

Changing its permission to 744 (group and public can read) ought to make it downloadable.

**Comment by DaxServer** [comment]
This is fixed now. Thanks!
